version: '3'
services:
        mica:
                image: obiba/mica:snapshot
                #build: .
                ports:
                        - "8872:8082"
                links:
                        - mongo
                environment:
                        - MICA_ADMINISTRATOR_PASSWORD=${MICA_ADMINISTRATOR_PASSWORD}
                        - MICA_ANONYMOUS_PASSWORD=${MICA_ANONYMOUS_PASSWORD}
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - OPAL_HOST=opal-demo.obiba.org
                        - OPAL_PORT=443
                        - AGATE_HOST=agate-demo.obiba.org
                        - AGATE_PORT=443
                volumes:
                        - ${MICA_DIR}:/srv
        mongo:
                image: mongo

