mica:
  image: obiba/mica:snapshot
  ports:
  - "8882:8082"
  links:
  - mongo
  - opal
  - agate
  environment:
  - MICA_ADMINISTRATOR_PASSWORD=password
  - MICA_ANONYMOUS_PASSWORD=password
  volumes:
  - /tmp/mica:/srv
opal:
  image: obiba/opal:snapshot
  ports:
  - "8880:8080"
  links:
  - mongo
  environment:
  - OPAL_ADMINISTRATOR_PASSWORD=password
  volumes:
  - /tmp/opal:/srv
agate:
  image: obiba/agate:snapshot
  ports:
  - "8881:8081"
  links:
  - mongo
  environment:
  - AGATE_ADMINISTRATOR_PASSWORD=password
  volumes:
  - /tmp/agate:/srv
mongo:
  image: mongo
