mica:
  image: obiba/mica:snapshot
  ports:
  - "8845:8445"
  - "8882:8082"
  links:
  - mongodb-obiba:mongo
  - opal
  - agate
opal:
  image: obiba/opal:snapshot
  ports:
  - "8843:8443"
  - "8880:8080"
  links:
  - mongodb-obiba:mongo
agate:
  image: obiba/agate:snapshot
  ports:
  - "8844:8444"
  - "8881:8081"
  links:
  - mongodb-obiba:mongo
mongodb-obiba:
  image: mongo