version: '3'
services:
        mica:
                #build: .
                image: obiba/mica:templates
                ports:
                        - "8845:8445"
                        - "8882:8082"
                links:
                        - mongo
                environment:
                        - JAVA_OPTS=-Xmx2G
                        - MICA_ADMINISTRATOR_PASSWORD=password
                        - MICA_ANONYMOUS_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                volumes:
                        - /tmp/mica:/srv
        mongo:
                image: mongo
