version: '3'
services:
        mica:
                build: .
                #image: obiba/mica:templates
                ports:
                        - "8835:8445"
                        - "8872:8082"
                links:
                        - mongo
                environment:
                        - JAVA_OPTS=-Xmx2G
                        - MICA_ADMINISTRATOR_PASSWORD=password
                        - MICA_ANONYMOUS_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - OPAL_HOST=opal
                        - OPAL_PORT=8443
                        - AGATE_HOST=agate
                        - AGATE_PORT=8444
                volumes:
                        - /tmp/templates-mica:/srv
        mongo:
                image: mongo
        opal:
                image: obiba/opal
                ports:
                        - "8833:8443"
                        - "8870:8080"
                links:
                        - mongo
                environment:
                        - OPAL_ADMINISTRATOR_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - AGATE_HOST=agate
                        - AGATE_PORT=8444
                volumes:
                        - /tmp/templates-opal:/srv
        agate:
                image: obiba/agate:1.6
                ports:
                        - "8834:8444"
                        - "8871:8081"
                links:
                        - mongo
                environment:
                        - AGATE_ADMINISTRATOR_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - RECAPTCHA_SITE_KEY=6Lfo7gYTAAAAAOyl8_MHuH-AVBzRDtpIuJrjL3Pb
                        - RECAPTCHA_SECRET_KEY=6Lfo7gYTAAAAADym-vSDvPBeBCXaxIprA0QXLk_b
                volumes:
                        - /tmp/templates-agate:/srv
