mica:
#  image: obiba/mica:3.0
  build: .
  ports:
  - "8845:8445"
  - "8882:8082"
  links:
  - mongo
  environment:
  - MICA_ADMINISTRATOR_PASSWORD=password
  - MICA_ANONYMOUS_PASSWORD=password
  volumes:
  - /tmp/mica:/srv
mongo:
  image: mongo
